export const products = [
  {
    id: 1,
    name: "Summer Occassion Shoes",
    price: 76,
    img: "men-1.jfif",
    category: "men",
  },
  {
    id: 2,
    name: "AD Sprint Black Running Shoes",
    price: 100,
    img: "men-2.jpg",
    category: "men",
  },
  {
    id: 3,
    name: "Puma Winter Shoes",
    price: 150,
    img: "men-3.jfif",
    category: "men",
  },
  {
    id: 4,
    name: "ClassNamey Casual Shoes",
    price: 80,
    img: "men-4.jpeg",
    category: "men",
  },
  {
    id: 5,
    name: "Handmade Leather Shoes",
    price: 60,
    img: "men-5.jpg",
    category: "men",
  },
  {
    id: 6,
    name: "Grey Joggers",
    price: 90,
    img: "men-6.jfif",
    category: "men",
  },
  {
    id: 7,
    name: "High Quality Genuine Leather Shoes",
    price: 250,
    img: "men-7.jpg",
    category: "men",
  },
  {
    id: 8,
    name: "Summer Flat Sneakers",
    price: 120,
    img: "men-8.jfif",
    category: "men",
  },
  {
    id: 9,
    name: "Men Sneakers",
    price: 110,
    img: "men-9.jpg",
    category: "men",
  },
  {
    id: 10,
    name: "Fly High Shoes",
    price: 110,
    img: "women-1.jpg",
    category: "women",
  },
  {
    id: 11,
    name: "PU Leather Casual Shoes",
    price: 320,
    img: "women-2.jfif",
    category: "women",
  },
  {
    id: 12,
    name: "Pink Running Shoes",
    price: 110,
    img: "women-3.jfif",
    category: "women",
  },
  {
    id: 13,
    name: "Spring Summer Flying Mesh",
    price: 90,
    img: "women-4.jpg",
    category: "women",
  },
  {
    id: 14,
    name: "Sandal Shoes",
    price: 60,
    img: "women-5.jfif",
    category: "women",
  },
  {
    id: 15,
    name: "Blue Spiderman LED Shoes",
    price: 70,
    img: "kids-1.jpg",
    category: "kids",
  },
  {
    id: 16,
    name: "Comfirtable Stylish Daily Wear",
    price: 75,
    img: "kids-2.jfif",
    category: "kids",
  },
  {
    id: 17,
    name: "Pink Luminous Shoes",
    price: 69,
    img: "kids-3.jpg",
    category: "kids",
  },
  {
    id: 18,
    name: "New Fasion Shoes",
    price: 98,
    img: "kids-4.jpg",
    category: "kids",
  },
  {
    id: 19,
    name: "Spiderman Light Up",
    price: 120,
    img: "kids-6.jpg",
    category: "kids",
  },
  {
    id: 20,
    name: "Striped Toddler LED Shoes",
    price: 130,
    img: "kids-7.jpg",
    category: "kids",
  },
  {
    id: 21,
    name: "Stylish Shoes",
    price: 135,
    img: "kids-8.jpg",
    category: "kids",
  },
];
